version: "3.1"

services:
  ngixn:
    image: nginx
    depends_on:
      - apionibus
      - phpmyadmin
    volumes:
        - "./conf/default.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
      - "443:443"
    links:
      - apionibus
      - phpmyadmin
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "12000:80"
    links:
      - db
    volumes:
      - /var/lib/mysql:/var/lib/mysql
  apionibus:
    image: golang:1.9
    ports:
      - "5000:5000"
    depends_on:
      - db
    working_dir: /go/src/github.com/rodrigo-brito/bus-api-go
    volumes:
      - ./:/go/src/github.com/rodrigo-brito/bus-api-go
    command: go run main.go
    restart: always
