version: "3.1"

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "12000:80"
    links:
      - "db:db"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
  go:
    image: golang:1.9
    ports:
      - "5000:5000"
    depends_on:
      - db
    working_dir: /go/src/github.com/rodrigo-brito/bus-api-go
    volumes:
      - ./:/go/src/github.com/rodrigo-brito/bus-api-go
    command: go run main.go
    restart: always
